export const accessTypes = Object.freeze({
    CHECK_ACCESS_FAILURE: "CHECK_ACCESS_FAILURE",
    CHECK_ACCESS_SUCCESS: "CHECK_ACCESS_SUCCESS",
    CLEAR_ACCESS_FAILURE: "CLEAR_ACCESS_FAILURE",
    CLEAR_ACCESS_SUCCESS: "CLEAR_ACCESS_SUCCESS"
})