export const headerTypes = {
    SET_HEADER_SIZE_SUCCESS: "SET_HEADER_SIZE_SUCCESS",
    SET_HEADER_SIZE_FAILURE: "SET_HEADER_SIZE_FAILURE",
    SET_MENU_OPEN_SUCCESS: "SET_MENU_OPEN_SUCCESS",
    SET_MENU_OPEN_FAILURE: "SET_MENU_OPEN_FAILURE"
}