export const authTypes = Object.freeze({
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE", 
    VERIFY_AUTH_REQUEST: "VERIFY_AUTH_REQUEST",
    VERIFY_AUTH_SUCCESS: "VERIFY_AUTH_SUCCESS",
    VERIFY_AUTH_FAILURE: "VERIFY_AUTH_FAILURE",
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
    RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
    CLEAR_AUTH_SUCCESS: "CLEAR_AUTH_SUCCESS",
    CLEAR_AUTH_FAILURE: "CLEAR_AUTH_FAILURE",

    //testing purposes
    TEST_LOGIN_SUCCESS: "TEST_LOGIN_SUCCESS",
    TEST_LOGIN_FAILURE: "TEST_LOGIN_FAILURE"

})